### ISSUE TITLE
Other cache provider

### ISSUE THREAD

**Issue by RaSeR** [himiklab/yii2-sitemap-module#10]
In apps could be many cache providers and the main one "cache" maybe use "memcached" instead of "fileCache", so maybe we can do smth with it? Maybe cache provider name option?

**Comment by himiklab** [comment]
Use `cacheKey` param in `Sitemap` module config.

**Comment by RaSeR** [comment]
Oh, my bad. Didn't see it in docs and didn't look close at source code( Thanks!

**Comment by RaSeR** [comment]
cacheKey used to mark cache not for use specific cache provider.

so i use:
```php
        'cache' => [
            'class' => 'yii\caching\MemCache',
        ],
        'fileCache' => [
            'class' => 'yii\caching\FileCache',
        ],
```
So my fileCache cacher is assigned to name "fileCache" instead for your "Yii::$app->cache"

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-sitemap-module/commit/5317e1da977243b0ba97366e393913fd15266fba

**Comment by RaSeR** [comment]
Yeap, that works right.
