### ISSUE TITLE
Module setup help

### ISSUE THREAD

**Issue by con322** [himiklab/yii2-sitemap-module#12]
Hi I want to use your module,

However I am unsure on a couple of things so it would be great if you could point me in the right direction.

Does the sitemap config go in my frontend config?

Also which parts do I need to change? Let say i have a CRUD such as frontend\modules\Articles 

As when I tried to install I got a white screen not to sure if this was misplacement of code or because it wasn't tweaked to fit in with my Article Model.

Thanks

**Comment by himiklab** [comment]
Hello!
Please show the code of your Article Model.

**Comment by con322** [comment]
Hi Below is part of my Article Model I think it should give you enough information to ry and help me out :)

`    public function rules()
    {
        return [
            [['user_id', 'title', 'summary', 'content', 'status', 'slug'], 'required'],
            [['slug'], 'unique'],
            [['user_id', 'status', 'category_id'], 'integer'],
            [['sub_title','summary', 'content'], 'string'],
            [['title', 'keywords', 'featured_img'], 'string', 'max' => 255],
            [['seo_title'], 'string', 'max' => 60],
            [['meta_desc'], 'string', 'max' => 155],
        ];
    }

    /**
     * Returns a list of behaviors that this component should behave as.
     *
     * @return array
     */

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            [
                'class' => SluggableBehavior::className(),
                'attribute' => 'title',
                'immutable' => true,
                'ensureUnique'=>true,
            ],
        ];
    }

    /**
     * Returns the attribute labels.
     *
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'Author'),
            'featured_img' => Yii::t('app', 'Featured Image'),
            'title' => Yii::t('app', 'Title'),
            'sub_title' => Yii::t('app', 'Sub Title'),
            'summary' => Yii::t('app', 'Summary'),
            'content' => Yii::t('app', 'Content'),
            'status' => Yii::t('app', 'Status'),
            'category_id' => Yii::t('app', 'Category'),
            'seo_title' => Yii::t('app', 'SEO Title (optional)'),
            'keywords' => Yii::t('app', 'Keywords (optional)'),
            'meta_desc' => Yii::t('app', 'Meta Description (optional)'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }
`

**Comment by himiklab** [comment]
Please add in `behaviors` method:
```php
[
            'class' => SitemapBehavior::className(),
            'dataClosure' => function ($model) {
                /** @var self $model */
                return [
                    'loc' => Url::to($model->slug, true),
                    'lastmod' => strtotime($model->updated_at),
                    'changefreq' => SitemapBehavior::CHANGEFREQ_DAILY,
                    'priority' => 0.5
                ];
            }
],
```

**Comment by con322** [comment]
Do I add that to my ArticleController within the public function behaviours section or in my app config?

Thanks

**Comment by con322** [comment]
How do I access my site map I have added the above code and below is my code in my app config

        'urlManager' => [
            'class' => 'yii\web\UrlManager',
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
                // your rules go here
                'article/<id:\d+>/<slug:[-a-zA-Z]+>' => 'article/view',
                'productitem/<id:\d+>/<slug:[-a-zA-Z]+>' => 'productitem/view',
                //sitemap rule below
                'pattern' => 'sitemap', 'route' => 'sitemap/default/index', 'suffix' => '.xml',

            ],
        ],
         'sitemap' => [
                'class' => 'himiklab\sitemap\Sitemap',
                'models' => [
                    // your models
                    '@app\models\article',
                    // or configuration for creating a behavior
                ],
                'urls'=> [
                    // your additional urls
                ],
                'enableGzip' => true, // default is false
                'cacheExpire' => 1, // 1 second. Default is 24 hours
            ],

**Comment by himiklab** [comment]
No! Add it (`'sitemap' => [...`) in `modules` section of your application's configuration file, аnd instead `@app\models\article` write full path to you model with namespace.

**Comment by con322** [comment]
Awesome, Cheers for the help all working :)

**Comment by svil1502** [comment]
Hello, I cant setup yii2-setup-module: http://itcrc.ru/sitemap.xml
My web.php(basic)
`<?php
use \himiklab\sitemap\behaviors\SitemapBehavior;

?>
<?php

$params = require __DIR__ . '/params.php';
$db = require __DIR__ . '/db.php';

$config = [
    'id' => 'basic',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'language' => 'ru-RU',
    'defaultRoute'=>'category/index',

    'aliases' => [
        '@bower' => '@vendor/bower-asset',
        '@npm'   => '@vendor/npm-asset',
    ],
    'modules' => [
        'admin' => [
            'class' => 'app\modules\admin\Module',
            'layout'=> 'admin',
             'defaultRoute'=>'order/index',
        ],
        'yii2images' => [
            'class' => 'rico\yii2images\Module',
            //be sure, that permissions ok
            //if you cant avoid permission errors you have to create "images" folder in web root manually and set 777 permissions
            'imagesStorePath' => 'upload/store', //path to origin images
            'imagesCachePath' => 'upload/cache', //path to resized copies
            'graphicsLibrary' => 'GD', //but really its better to use 'Imagick'
            'placeHolderPath' => '@webroot/upload/store/no-image.png', // if you want to get placeholder when image not exists, string will be processed by Yii::getAlias
            'imageCompressionQuality' => 100, // Optional. Default value is 85.

        ],
        'sitemap' => [
            'class' => 'himiklab\sitemap\Sitemap',
            'models' => [
                // your models
//                'app\models\Category',
//                'app\models\Blog',
//                'app\models\Brand',
//                'app\models\Cart',
//                'app\models\Comment',
                //'app\modules\news\models\News',
                // or configuration for creating a behavior
                [
                   // 'class' => 'app\modules\news\models\News',
                    'behaviors' => [
                        'sitemap' => [
                            'class' => SitemapBehavior::className(),
                            'scope' => function ($model) {
                                /** @var \yii\db\ActiveQuery $model */
                                $model->select(['url', 'lastmod']);
                                $model->andWhere(['is_deleted' => 0]);
                            },
                            'dataClosure' => function ($model) {
                                /** @var self $model */
                                return [
                                    'loc' => Url::to($model->url, true),
                                    'lastmod' => strtotime($model->lastmod),
                                    'changefreq' => SitemapBehavior::CHANGEFREQ_DAILY,
                                    'priority' => 0.8
                                ];
                            }
                        ],
                    ],
                ],
            ],
            'urls'=> [
                // your additional urls
                [
                    'loc' => '/news/index',
                    'changefreq' => \himiklab\sitemap\behaviors\SitemapBehavior::CHANGEFREQ_DAILY,
                    'priority' => 0.8,
                    'news' => [
                        'publication'   => [
                            'name'          => 'Example Blog',
                            'language'      => 'en',
                        ],
                        'access'            => 'Subscription',
                        'genres'            => 'Blog, UserGenerated',
                        'publication_date'  => 'YYYY-MM-DDThh:mm:ssTZD',
                        'title'             => 'Example Title',
                        'keywords'          => 'example, keywords, comma-separated',
                        'stock_tickers'     => 'NASDAQ:A, NASDAQ:B',
                    ],
                    'images' => [
                        [
                            'loc'           => 'http://example.com/image.jpg',
                            'caption'       => 'This is an example of a caption of an image',
                            'geo_location'  => 'City, State',
                            'title'         => 'Example image',
                            'license'       => 'http://example.com/license',
                        ],
                    ],
                ],
            ],
            'enableGzip' => true, // default is false
            'cacheExpire' => 1, // 1 second. Default is 24 hours
        ],
    ],
    'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            // 'cookieValidationKey' => 'OFwTWd2ye4uytMHdXAmuLG3jtikD_3zw',
            'cookieValidationKey' => 'yYy4YYYX8lYyYyQOl8vOcO6ROo7i8twO',
           // 'baseUrl' => '',
        ],
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'user' => [
            'identityClass' => 'app\models\User',
            'enableAutoLogin' => true,
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            // send all mails to a file by default. You have to set
            // 'useFileTransport' to false and configure a transport
            // for the mailer to send real emails.
            'useFileTransport' => false, //true когда почта реально не будет отправляться,
            //если надо отправлять - устанавливаем в false и устанавливаем конфигурацию
            //smtp сервера - пример есть в непереводной документации
            //https://www.yiiframework.com/extension/yiisoft/yii2-swiftmailer/doc/api/2.2/yii-swiftmailer-mailer
        //    'host' => 'smtp.gmail.com',
          //  'username' => 'username',
           // 'password' => 'password',
            'transport' => [
                'class' => 'Swift_SmtpTransport',
                'host' => 'smtp.mail.ru',
                'username' => 'developersvil1502',
                'password' => 'my_password',
                'port' => '465',
                'encryption' => 'ssl',
            ],

        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => $db,

        'urlManager' => [
            'enablePrettyUrl' => true, //
            'showScriptName' => false,

            //для gii
//            'enablePrettyUrl' => false,
//           'showScriptName' => true,
            'rules' => [
                'category/<id:\d+>/page/<page:\d+>' => 'category/view',
                'category/<id:\d+>' => 'category/view',
                'product/<id:\d+>' => 'product/view',
                'search' => 'category/search',
                'cart/<id:\d+>' => 'cart/pi',
                'brand/<id:\d+>' => 'brand/view',
                'test/<id:\d+>/page/<page:\d+>' => 'test/page',
                'test/<id:\d+>' => 'test/page',
                'footer/<id:\d+>' => 'footer/hits',
                '<_m:debug>/<_c:\w+>/<_a:\w+>' => '<_m>/<_c>/<_a>',
                'pattern' => 'sitemap', 'route' => 'sitemap/default/index', 'suffix' => '.xml',
              //  '<id:([0-9])+>/images/image-by-item-and-alias' => 'yii2images/images/image-by-item-and-alias',

               //    '' => 'site/index',
               // '<controller:\w+>/<action:\w+>/' => '<controller>/<action>',
            ],
        ],
        'yandexMapsApi' => [
            'class' => 'mirocow\yandexmaps\Api',
        ],


    ],
    'controllerMap' => [
        'elfinder' => [
            'class' => 'mihaildev\elfinder\PathController',
            'access' => ['@'],
            'root' => [
              //  'baseUrl'=>'/web',
                'path' => 'upload/global',
                'name' => 'Global'
            ],
            'watermark' => [
                'source'         => __DIR__.'/logo.png', // Path to Water mark image
                'marginRight'    => 5,          // Margin right pixel
                'marginBottom'   => 5,          // Margin bottom pixel
                'quality'        => 95,         // JPEG image save quality
                'transparency'   => 70,         // Water mark image transparency ( other than PNG )
                'targetType'     => IMG_GIF|IMG_JPG|IMG_PNG|IMG_WBMP, // Target image formats ( bit-field )
                'targetMinPixel' => 200         // Target image minimum pixel size
            ]
        ]
    ],
    'params' => $params,
];

if (YII_ENV_DEV) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = [
        'class' => 'yii\debug\Module',
        // uncomment the following to add your IP if you are not connecting from localhost.
        //'allowedIPs' => ['127.0.0.1', '::1'],
    ];

    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = [
        'class' => 'yii\gii\Module',
        // uncomment the following to add your IP if you are not connecting from localhost.
        //'allowedIPs' => ['127.0.0.1', '::1'],
    ];
}

return $config;
`
I add in models Brand, Category and others :`

namespace app\models;
use yii\db\ActiveRecord;
use himiklab\sitemap\behaviors\SitemapBehavior;
public function behaviors()
    {
        return [
            'sitemap' => [
                'class' => SitemapBehavior::className(),
                'scope' => function ($model) {
                    /** @var \yii\db\ActiveQuery $model */
                    $model->select(['url', 'lastmod']);
                    $model->andWhere(['is_deleted' => 0]);
                },
                'dataClosure' => function ($model) {
                    /** @var self $model */
                    return [
                        'loc' => Url::to($model->url, true),
                        'lastmod' => strtotime($model->lastmod),
                        'changefreq' => SitemapBehavior::CHANGEFREQ_DAILY,
                        'priority' => 0.8
                    ];
                }
            ],
        ];
    }`
What is wrong?
