### ISSUE TITLE
Is it possible to split/several sitemaps?

### ISSUE THREAD

**Issue by con322** [himiklab/yii2-sitemap-module#13]
Sorry if this question has been answered some where in the documentation.

Is it possible to say have the following setup:

sitemap.xml <- static pages., main pages 
article.xml <- Article Model

**Comment by himiklab** [comment]
Use two XML Sitemap Module.

**Comment by con322** [comment]
Okay thanks, how do I setup my URL Manager to cater for several xml sitemaps.

The example/default is as follow:

    ['pattern' => 'sitemap', 'route' => 'sitemap/default/index', 'suffix' => '.xml'],

Do I need to create additional views per sitemap/xml?

**Comment by himiklab** [comment]
``
['pattern' => 'sitemapOne', 'route' => 'sitemapOne/default/index', 'suffix' => '.xml'],
['pattern' => 'sitemapTwo', 'route' => 'sitemapTwo/default/index', 'suffix' => '.xml'],
``
and in `modules` section:
``
'modules' => [
    'sitemapOne' => [
        'class' => 'himiklab\sitemap\Sitemap',
....
'modules' => [
    'sitemapTwo' => [
        'class' => 'himiklab\sitemap\Sitemap',
....
``
