### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by fabiomlferreira** [himiklab/yii2-sitemap-module#18]
I can't figured out how to create a good sitemap in a website with multiple languages, I need something like this: https://support.google.com/webmasters/answer/2620865?hl=en

This is possible with this module?

**Comment by himiklab** [comment]
Yes, you must use the main site map file (as https://support.google.com/webmasters/answer/2620865?hl=en) and several sitemap modules for different languages.

**Comment by vkaterusha** [comment]
Hi
Could you explain what you meant by "several sitemap modules" ?
I need to be able to indicate alternate languages for same url in sitemap file.

Thank you

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-sitemap-module/commit/e680cb50049102c47342d27f497f77d8c0e447b3
