### ISSUE TITLE
application/xml overrides by text/html

### ISSUE THREAD

**Issue by Bdiang** [himiklab/yii2-sitemap-module#20]
You should add die after echo $sitemapData; because header content type overrides by text/html

**Comment by himiklab** [comment]
Try this version https://github.com/himiklab/yii2-sitemap-module/releases/tag/1.1.2

**Comment by Bdiang** [comment]
Неа. Непомогло. Два раза проверил с очисткой кеша. Может На момент того комита другая версия yii была. Но в текущей так не работает. Помог только die. Правда, пришлось форкнуть и перекинуть в папку common, чтобы при обновлениях не перетиралось.

**Comment by himiklab** [comment]
Проверил, отдаётся "application/xml",  ```Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;
$headers->add('Content-Type', 'application/xml');``` плностью решают проблму, может дело в настройках сервера или нестандартной конфигурации проекта?
