### ISSUE TITLE
Grids + pagination = how to?

### ISSUE THREAD

**Issue by vadim-bulochnik** [himiklab/yii2-sitemap-module#23]
Hello!

Seems there is no support for pagination in GridView/ListView. How I can take into account links to all grid pages?

Thanks,
Vadim

**Comment by himiklab** [comment]
Это расширение работает с базой данных, и берёт все данные которые Вы ему передадите.

**Comment by vadim-bulochnik** [comment]
Yes, I understand. But no possibility to use data provider to create pagination, like in this extension: https://github.com/xjflyttp/yii2-sitemap

**Comment by himiklab** [comment]
Yes, only ActiveRecord.
