### ISSUE TITLE
Url encoding

### ISSUE THREAD

**Issue by soulhunter1987** [himiklab/yii2-sitemap-module#27]
If creating an url with ampersand (/some/path?param1=x&param2=y) - invalid XML is produced. Final URL shoud be html encoded in the view.

**Comment by iovzt** [comment]
I got the same error. Please fix it.

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-sitemap-module/commit/8fee59b5faa3b60016da7630c15862580b0217f1
