### ISSUE TITLE
Creating Image sitemap from Model

### ISSUE THREAD

**Issue by bhu1st** [himiklab/yii2-sitemap-module#28]
How to go about building sitemaps for Images using Model ?  
https://support.google.com/webmasters/answer/178636?hl=en

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-sitemap-module/commit/4b0d6bc840e78083524e7aaeaec600ff1101d8a2#diff-a746dc5f42af4b4ddc419e0981c004a7
