### ISSUE TITLE
date format in lastmod

### ISSUE THREAD

**Issue by disasterovich** [himiklab/yii2-sitemap-module#7]
Hello! I use your module.

In README.md written following:

'lastmod' => strtotime($model->lastmod),

I think it would be correct so:

'lastmod' =>  date('c', $model->lastmod),

**Comment by himiklab** [comment]
Hello!
This allows the model to store the date in any format that is able to understand the function strtotime. At the date of the module must always be transmitted in the UNIX format.

**Comment by con322** [comment]
Just out on interest how come 

    strtotime($model->updated_at)

Creates 

    <lastmod>1970-01-01T01:00:00+01:00</lastmod>

But 

    'lastmod' => date('c', $model->updated_at),

Creates

   <lastmod>2015-05-08T01:25:13+02:00</lastmod>

Is it better to use strtotime if so do I need to change my timestamp behaviour?
